name: Update Phishtank Database JSON

on:
  workflow_dispatch:
  repository_dispatch:
  #schedule:
    #- cron: '0 0 * * *'
    
jobs:
  update-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PHISH_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Download and extract phishtank data
        run: |
          curl -s http://data.phishtank.com/data/online-valid.json.gz | gunzip > phishtank_urls.json

      - name: Extract URLs
        run: |
          jq '[.[].url]' phishtank_urls.json > temp.json && mv temp.json phishtank_urls.json

      - name: Check for changes
        id: changes
        run: |
          git add phishtank_urls.json
          if git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.PHISH_GITHUB_TOKEN }}
        run: |
          git config --global user.name "vishwas-r"
          git config --global user.email "vishwas.r.jnv@gmail.com"
          git remote set-url origin https://${{ secrets.PHISH_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git commit -m "Update phishtank URLs [$(date +'%Y-%m-%d %H:%M')]"
          git push origin HEAD:main
